version: 2
jobs:
  build:
    working_directory: ~/vscode-graphql
    docker:
      - image: circleci/node:8.12.0-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: package
          command: npm run package
      - run:
          command: |
            mkdir -p /tmp/artifacts
            cp *.vsix /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
