name: automatic-release

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Setup GIT
        run: |
          git config --global user.email "prismabots@gmail.com"
          git config --global user.name "Prismo"
          git remote add github "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" || true
      - name: Bump version
        id: bump
        run: |
          npm version patch
      - name: Push to master
        run: |
          git push github HEAD:"${GITHUB_REF}"
