name: automatic-release

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  prerelease:
    if: endsWith(github.ref, '/master')
    name: Create prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci

      - name: Bump version
        id: bump
        run: |
          ./node_modules/.bin/vsce publish --pre
