name: Automatic Publish

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  PAT: ${{ secrets.PAT }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Publish Extension as Patch
        run: npm run vsce:publish
