name: Automatic Publish

on:
  push:
    branches:
      - master
      - feat_automate_release

env:
  PAT: ${{ secrets.PAT }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Publish Extension as Patch
        run: npm run vsce:publish
